name: Build, Sign, and Release InterviewAssistant

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          if exist requirements.txt (
              pip install -r requirements.txt
          ) else (
              echo "No requirements.txt found, skipping..."
          )

      - name: Build EXE
        run: pyinstaller --onefile it.py --name InterviewAssistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: List dist folder (debug)
        run: dir dist

      # ✅ Ensure signtool exists (important fix)
      - name: Ensure signtool is available
        run: |
          $signtool = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64\signtool.exe"
          if (Test-Path $signtool) {
              echo "signtool found at $signtool"
              echo "C:\Program Files (x86)\Windows Kits\10\bin\10.0.22621.0\x64" >> $env:GITHUB_PATH
          } else {
              echo "signtool not found — installing Windows SDK tools..."
              choco install windows-sdk-10-version-2004-all -y
          }

      - name: Sign EXE (optional self-signed)
        if: success() && env.SIGNING_CERT_PASSWORD != ''
        run: |
          certutil -f -p ${{ secrets.SIGNING_CERT_PASSWORD }} -importpfx "signing-cert.pfx"
          signtool sign /f signing-cert.pfx /p ${{ secrets.SIGNING_CERT_PASSWORD }} /tr http://timestamp.digicert.com /td sha256 /fd sha256 dist/InterviewAssistant.exe
        env:
          SIGNING_CERT_PASSWORD: ${{ secrets.SIGNING_CERT_PASSWORD }}

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: InterviewAssistant-signed
          path: dist/InterviewAssistant.exe

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/InterviewAssistant.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
