name: Build and Sign App

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt  # if you have other packages

      - name: Build EXE
        run: pyinstaller --onefile it.py
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Sign EXE (self-signed)
        run: |
          certutil -f -p ${{ secrets.SIGNING_CERT_PASSWORD }} -importpfx "signing-cert.pfx"
          signtool sign /f signing-cert.pfx /p ${{ secrets.SIGNING_CERT_PASSWORD }} /tr http://timestamp.digicert.com /td sha256 /fd sha256 dist/interviewAssistant.exe
        env:
          SIGNING_CERT_PASSWORD: ${{ secrets.SIGNING_CERT_PASSWORD }}

      - name: Upload signed artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-exe
          path: dist/interviewAssistant.exe
